apiVersion: v1
kind: service
metadata:
  name: docker-demo
  labels:
    app: docker-demo
spec:
  type: NodePort
  selector:
    app:  
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-demo
spec:
  selector:
    matchLabels:
      app: docker-demo
  replicas: 1
  template:
    metadata:
      labels:
        app: docker-demo
    spec:
      containers:
        - name: deployment-demo
          image: vihaan2023/docker-kubernetes-demo1:latest
          ports:
            - containerPort: 8010
          livenessProbe:
            httpGet:
              path: /dockerTest
              port: 8010
            initialDelaySeconds: 30
            timeoutSeconds: 1